server: https://t.jubaozan.cn/
variables:
  userhost: https://u.jubaozan.cn
  shophost: https://trade.jubaozan.cn
  prehost: https://pre.auth.2mhn.cn
  siteId : 2136
browser:
  name: chrome
  mode: normal #headless表示谷歌headles模式, normal，grid,docker
user01:
  name: sjsdmz
  password: a111111
