server: https://t.jubaozan.cn/
variables:
  userhost: https://u.jubaozan.cn
  shophost: https://trade.jubaozan.cn
  siteId : 1123
browser:
  name: chrome
  mode: normal #headless表示谷歌headles模式, normal，grid,docker
user01:
  name: sjsdmz
  password: a111111
  cell: 23423423
